In [1]:
a=10
a

10

In [3]:
a=10
b=20
a
b

20

In [4]:
a=[22,30,40,50]
a

[22, 30, 40, 50]

In [6]:
d=np.mean(score)
d

np.float64(35.5)

In [7]:
print(np.max(score))

50


In [9]:
f=np.zeros([3,4])
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
f=np.ones([5,5])
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
g=np.random.rand(5,4)
g

array([[0.21092466, 0.16795172, 0.05476279, 0.15572452],
       [0.10059954, 0.72564168, 0.17425619, 0.31662324],
       [0.98731232, 0.30231283, 0.73248448, 0.25176805],
       [0.40848575, 0.82613355, 0.11026496, 0.40081555],
       [0.33514697, 0.67317269, 0.83678999, 0.07396078]])

In [13]:
a=np.array([11,22,33,44,1,3,6,7,8,9])
d=np.reshape(a,(2,5))
d

array([[11, 22, 33, 44,  1],
       [ 3,  6,  7,  8,  9]])

In [14]:
c=b=np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
c=np.array([11,22,33,44,55,66])
d=c[1:5]
d

array([22, 33, 44, 55])

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a-b

array([-3, -3, -3])

In [22]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [23]:
a = np.array([[1,2,3],[6,7,8]])
b = np.array([[4,5],
              [8,4],
              [6,5]])
c=np.dot(a,b)
c

array([[ 38,  28],
       [128,  98]])

In [24]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
arr = np.array([5,2,8,1,9])
print(np.sort(arr))

[1 2 5 8 9]


In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [27]:
arr = np.array([1,2,2,3,4,4,5])
d=np.unique(arr)
d

array([1, 2, 3, 4, 5])

In [29]:
arr = np.array([1,2,2,3,4,4,5])
d=np.unique(arr)
d

array([1, 2, 3, 4, 5])

In [30]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]
